name: SwiftLocationWithPromisesJobs

on:
  push:
    branches:
      - main

jobs:
  test:
    name: SwiftLocationWithPromisesBuild
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2
      - name: Build
        run: swift build -v
